-- Creating Database
CREATE DATABASE q4_2025;

-- Creating Table
-- INFOTABLE
CREATE TABLE INFOTABLE (
    ACCESSION_NUMBER VARCHAR(50),
    INFOTABLE_SK BIGINT,
    NAMEOFISSUER VARCHAR(500),
    TITLEOFCLASS VARCHAR(500),
    CUSIP VARCHAR(50),
    FIGI VARCHAR(100),
    `VALUE` BIGINT,
    SSHPRNAMT BIGINT,
    SSHPRNAMTTYPE VARCHAR(50),
    PUTCALL VARCHAR(50),
    INVESTMENTDISCRETION VARCHAR(50),
    OTHERMANAGER VARCHAR(500),
    VOTING_AUTH_SOLE BIGINT,
    VOTING_AUTH_SHARED BIGINT,
    VOTING_AUTH_NONE BIGINT
);                                                                          

-- COVERPAGE
CREATE TABLE COVERPAGE (
    ACCESSION_NUMBER VARCHAR(50),
    REPORTCALENDARORQUARTER VARCHAR(60),
    ISAMENDMENT VARCHAR(50),
    AMENDMENTNO VARCHAR(100),
    AMENDMENTTYPE VARCHAR(50),
    CONFDENIEDEXPIRED VARCHAR(50),
    DATEDENIEDEXPIRED VARCHAR(50),
    DATEREPORTED VARCHAR(50),
    REASONFORNONCONFIDENTIALITY TEXT,
    FILINGMANAGER_NAME VARCHAR(500),
    FILINGMANAGER_STREET1 VARCHAR(500),
    FILINGMANAGER_STREET2 VARCHAR(500),
    FILINGMANAGER_CITY VARCHAR(500),
    FILINGMANAGER_STATEORCOUNTRY VARCHAR(100),
    FILINGMANAGER_ZIPCODE VARCHAR(50),
    REPORTTYPE VARCHAR(500),
    FORM13FFILENUMBER VARCHAR(200),
    CRDNUMBER VARCHAR(200),
    SECFILENUMBER VARCHAR(200),
    PROVIDEINFOFORINSTRUCTION5 VARCHAR(50),
    ADDITIONALINFORMATION TEXT
);

-- Data Import
-- Infotable
SET GLOBAL local_infile = 1;
LOAD DATA LOCAL INFILE 'C:/Users/Raav/Desktop/Work Stuff/2025-Q4-13F/INFOTABLE.tsv'
INTO TABLE INFOTABLE
FIELDS TERMINATED BY '\t' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

---------------------------------------------------------------------------------

-- Coverpage
LOAD DATA LOCAL INFILE 'C:/Users/Raav/Desktop/Work Stuff/2025-Q4-13F/COVERPAGE.tsv'
INTO TABLE COVERPAGE
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;
